trigger: 
- noon  

pool: 
  name: DevOps_Infra

  - task: PowerShell@2
  inputs:
    filePath: 'terraform init'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'terraform plan'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'terraform apply -auto-approve'